apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  imagePullSecrets:
    - name: ecr-creds
  containers:
    - name: webapp
      image: 058264412508.dkr.ecr.us-east-1.amazonaws.com/clo835-a2-webapp:v0.2
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: mysql-service
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: passwors
        - name: DATABASE
          value: employees
