name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push webapp image
        run: |
          docker build -t webapp:latest -f Dockerfile .
          docker tag webapp:latest ${{ steps.login-ecr.outputs.registry }}/clo835-a1-webapp:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/clo835-a1-webapp:latest

      - name: Build, tag, and push mysql image
        run: |
          docker build -t mysql:latest -f Dockerfile_mysql .
          docker tag mysql:latest ${{ steps.login-ecr.outputs.registry }}/clo835-a1-mysql:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/clo835-a1-mysql:latest

